source 'https://github.com/CocoaPods/Specs.git'

target 'Oscar_Example', :exclusive => true do
  pod "Oscar", :path => "../"
  pod 'RXPromise', '~> 0.13'
  pod 'CocoaLumberjack'
end

target 'Oscar_Tests', :exclusive => true do
  pod "Oscar", :path => "../"

  pod 'Kiwi'
end
